# Generated by Django 5.0.2 on 2024-04-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team1_bowlers",
                    models.ManyToManyField(
                        related_name="team1_matches", to="predict2.bowler"
                    ),
                ),
                (
                    "team1_players",
                    models.ManyToManyField(
                        related_name="team1_matches", to="predict2.batsman"
                    ),
                ),
                (
                    "team2_bowlers",
                    models.ManyToManyField(
                        related_name="team2_matches", to="predict2.bowler"
                    ),
                ),
                (
                    "team2_players",
                    models.ManyToManyField(
                        related_name="team2_matches", to="predict2.batsman"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="predict2.venue"
                    ),
                ),
            ],
        ),
    ]
